// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Describes a public configurable-agent payload without persistence audit metadata.
 */
export type Agent = { id: string; name: string; description: string };
