// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Requests the bounded catalog for one project or task context.
 */
export type GetSpecCatalogRequest = { target: SpecTarget };

/**
 * Requests one catalog-authorized Markdown document.
 */
export type ReadSpecRequest = { target: SpecTarget; relativePath: string };

/**
 * Returns the raw, read-only Markdown payload and its exact size.
 */
export type ReadSpecResponse = {
  relativePath: string;
  content: string;
  byteSize: number;
};

/**
 * Returns the bounded Markdown document index.
 */
export type SpecCatalogResponse = {
  documents: Array<SpecDocument>;
  truncated: boolean;
};

/**
 * Describes one Markdown document assigned to an automatically detected source.
 */
export type SpecDocument = {
  relativePath: string;
  sourceRelativePath: string;
  workflow: SpecWorkflow;
  byteSize: number;
};

/**
 * Selects the project checkout or task workspace whose specification documents are managed.
 */
export type SpecTarget = { "kind": "project"; projectId: string } | {
  "kind": "task";
  taskId: string;
};

/**
 * Identifies the workflow that owns a specification source.
 */
export type SpecWorkflow =
  | { "kind": "open_spec" }
  | { "kind": "superpowers" }
  | { "kind": "custom"; name: string };

/**
 * Starts specification-aware workspace file monitoring for one target.
 */
export type WatchSpecsRequest = { target: SpecTarget };
