// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Commits every current change in one task-owned worktree.
 */
export type CommitTaskChangesRequest = { taskId: string; message: string };

/**
 * Returns the commit created from the task worktree.
 */
export type CommitTaskChangesResponse = { commitId: string; summary: string };

/**
 * Identifies which task diff should be computed.
 */
export type GetTaskDiffRequest = { taskId: string; scope: TaskDiffScope };

/**
 * Returns one standard unified patch and the revisions needed to render it.
 */
export type GetTaskDiffResponse = {
  baseCommitId: string;
  headCommitId: string;
  patch: string;
};

/**
 * Pushes the current task branch to its default remote.
 */
export type PushTaskBranchRequest = { taskId: string };

/**
 * Returns the branch and remote updated by a successful push.
 */
export type PushTaskBranchResponse = { branchName: string; remoteName: string };

/**
 * Selects which Git layer should be rendered in the task review surface.
 */
export type TaskDiffScope = "branch" | "unstaged" | "staged" | "committed";
