// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Commits only the currently staged change set in one workspace's checkout.
 *
 * The caller must stage changes first (see `StageWorkspaceChanges`) because
 * this operation never modifies the index.
 */
export type CommitWorkspaceChangesRequest = {
  workspaceId: string;
  message: string;
};

/**
 * Returns the commit created from the workspace checkout.
 */
export type CommitWorkspaceChangesResponse = {
  commitId: string;
  summary: string;
};

/**
 * Identifies which workspace diff should be computed.
 */
export type GetWorkspaceDiffRequest = {
  workspaceId: string;
  scope: WorkspaceDiffScope;
};

/**
 * Returns one standard unified patch and the revisions needed to render it.
 *
 * `base_commit_id` is absent when the workspace has no recorded baseline (a
 * project's main checkout, or a historical worktree whose creation commit was
 * never recorded) - only meaningful for the `Branch`/`Committed` scopes.
 */
export type GetWorkspaceDiffResponse = {
  baseCommitId: string | null;
  headCommitId: string;
  patch: string;
};

/**
 * Identifies which workspace staging status should be read.
 */
export type GetWorkspaceStatusRequest = { workspaceId: string };

/**
 * Returns the structured per-file staging state of one workspace checkout.
 */
export type GetWorkspaceStatusResponse = {
  entries: Array<WorkspaceStatusEntry>;
};

/**
 * Pushes the current workspace branch to its default remote.
 */
export type PushWorkspaceBranchRequest = { workspaceId: string };

/**
 * Returns the branch and remote updated by a successful push.
 */
export type PushWorkspaceBranchResponse = {
  branchName: string;
  remoteName: string;
};

/**
 * Stages selected changes in one workspace checkout.
 *
 * An empty `paths` list stages every current change in the workspace.
 */
export type StageWorkspaceChangesRequest = {
  workspaceId: string;
  /**
   * Repo-relative paths to stage; an empty list stages every current change.
   */
  paths: Array<string>;
};

/**
 * Returns the paths that were staged in one workspace checkout.
 */
export type StageWorkspaceChangesResponse = { stagedPaths: Array<string> };

/**
 * Unstages selected changes in one workspace checkout.
 *
 * An empty `paths` list is a defensive no-op and unstages nothing.
 */
export type UnstageWorkspaceChangesRequest = {
  workspaceId: string;
  /**
   * Repo-relative paths to unstage; an empty list unstages nothing.
   */
  paths: Array<string>;
};

/**
 * Returns the paths that were unstaged in one workspace checkout.
 */
export type UnstageWorkspaceChangesResponse = { unstagedPaths: Array<string> };

/**
 * Selects which Git layer should be rendered in the workspace review surface.
 */
export type WorkspaceDiffScope = "branch" | "unstaged" | "staged" | "committed";

/**
 * Represents one changed file's staging state.
 */
export type WorkspaceStatusEntry = {
  path: string;
  isStaged: boolean;
  isUntracked: boolean;
};
