// This file was generated by `cargo xtask export-contracts`. Do not edit this file manually.
import { listen } from "@tauri-apps/api/event";
import type { MarketplaceAutoSyncEvent } from "@ora/contracts";

/** Subscribes to the Desktop-owned automatic marketplace refresh route. */
export function onMarketplaceAutoSyncChanged(listener: (event: MarketplaceAutoSyncEvent) => void): Promise<() => void> {
  return listen<MarketplaceAutoSyncEvent>("marketplace-auto-sync-changed", (event) => listener(event.payload));
}
