// This file was generated by `cargo xtask export-contracts`. Do not edit this file manually.
import type { MarketplaceAutoSyncEvent } from "@ora/contracts";

// Actual serde output, checked against the generated DTO and consumed by adapter tests.
export const marketplaceAutoSyncWire = { route: "marketplace-auto-sync-changed", payloads: [{"kind":"started"},{"kind":"finished"}] } as const satisfies { route: string; payloads: readonly MarketplaceAutoSyncEvent[] };
