// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Holds back manual synchronization while the host rebuilds the cached marketplace listing.
 */
export type MarketplaceAutoSyncEvent = { "kind": "started" } | {
  "kind": "finished";
};
