// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Stable child-process failure classification carried in JSON-RPC error data.
 */
export type ChildProcessErrorKind =
  | "invalid_params"
  | "invalid_command"
  | "package_command_missing"
  | "invalid_package_command"
  | "not_found"
  | "program_not_found"
  | "io";

/**
 * Notification describing how one host-managed process ended.
 */
export type ChildProcessExit = {
  processId: string;
  code: number | null;
  signal: number | null;
};

/**
 * Parameters shared by operations that address one spawned process.
 */
export type ChildProcessIdParams = { processId: string };

/**
 * Notification carrying one base64-encoded stdout or stderr chunk.
 */
export type ChildProcessOutput = { processId: string; bytesBase64: string };

/**
 * Wire payload for spawning a host-managed process.
 */
export type ChildProcessSpawnParams = {
  command?: string;
  packageCommand?: string;
  args: Array<string>;
  cwd: string | null;
  env: { [key in string]: string };
};

/**
 * Result identifying one spawned process inside its plugin generation.
 */
export type ChildProcessSpawnResult = { processId: string; pid: number | null };

/**
 * Parameters for writing one base64-encoded byte chunk to process stdin.
 */
export type ChildProcessWriteParams = {
  processId: string;
  bytesBase64: string;
};
