// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Exact Target and Resource set sent around one mutation attempt.
 */
export type AgentEffectCoordinationContext = {
  targetId: string;
  resourceIds: Array<string>;
};

/**
 * Exact immutable Target projection whose readiness the Agent must confirm.
 */
export type AgentEffectReadinessContext = {
  targetId: string;
  generation: number;
  consumerRevisionId: string;
  projectionDigest: string;
};
