// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Selects the runtime barrier required before Ora mutates one declared Resource.
 */
export type PluginEffectCoordination =
  | "uninterrupted"
  | "quiesce_before_mutation";

/**
 * One Workspace-relative Effect Resource included in immutable plugin registration.
 */
export type PluginEffectResource = {
  workspaceRelativePath: string;
  materializationFormat: string;
  coordination: PluginEffectCoordination;
};

/**
 * Wire payload of the `ora/register` notification.
 */
export type PluginRegistrationParams = {
  methods: Array<string>;
  emits: Array<string>;
  effectResources?: Array<PluginEffectResource>;
};
