// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Closed set of entry kinds visible through plugin storage.
 */
export type StorageEntryKind = "file" | "directory";

/**
 * Stable storage failure classification carried in JSON-RPC error data.
 */
export type StorageErrorKind =
  | "invalid_params"
  | "invalid_path"
  | "not_found"
  | "too_large"
  | "io";

/**
 * One regular file or directory returned by storage listing.
 */
export type StorageListEntry = {
  name: string;
  kind: StorageEntryKind;
  size_bytes: number;
};

/**
 * Result of listing one storage directory.
 */
export type StorageListResult = { entries: Array<StorageListEntry> };

/**
 * Parameters for a storage operation addressed by logical path.
 */
export type StoragePathParams = { path: string };

/**
 * Result of reading one storage file.
 */
export type StorageReadResult = { bytes_base64: string };

/**
 * Parameters for replacing one storage file from base64-encoded bytes.
 */
export type StorageWriteParams = { path: string; bytes_base64: string };
